default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: aviato_development

test:
  <<: *default
  database: aviato_test

production:
  <<: *default
  database: aviato_production
